# Default Zenoh Recorder Configuration

# Zenoh connection settings
zenoh:
  mode: peer  # peer, client, or router
  connect:
    endpoints:
      - tcp/localhost:7447

# Storage backend configuration
storage:
  backend: reductstore
  reductstore:
    url: http://localhost:8383
    bucket_name: zenoh_recordings
    api_token: ${REDUCT_API_TOKEN}  # Optional, use env var
    timeout_seconds: 300
    max_retries: 3

# Recorder settings
recorder:
  device_id: ${DEVICE_ID:-recorder-001}
  
  # Buffer flush policies
  flush_policy:
    max_buffer_size_bytes: 10485760      # 10 MB
    max_buffer_duration_seconds: 10      # 10 seconds
    min_samples_per_flush: 10
  
  # Compression settings
  compression:
    default_type: zstd  # none, lz4, zstd
    default_level: 2    # 0-4 (fastest to slowest)
    
    # Per-topic compression overrides (optional)
    # per_topic:
    #   "/camera/**":
    #     type: lz4
    #     level: 1
    #   "/lidar/**":
    #     type: zstd
    #     level: 3
  
  # Worker thread pool
  workers:
    flush_workers: 4      # Concurrent flush operations
    queue_capacity: 1000  # Max pending flush tasks
  
  # Control interface
  control:
    key_prefix: recorder/control
    status_key: recorder/status/**
    timeout_seconds: 30

# Logging configuration
logging:
  level: info  # trace, debug, info, warn, error
  format: text  # text, json

