# Filesystem Backend Configuration (Production Ready)
# Useful for offline/edge recording scenarios
#
# This backend writes MCAP files directly to the local filesystem:
# - No external dependencies required
# - Automatic directory organization by entry name
# - JSON metadata files with labels
# - Each flush creates a new file: {timestamp}.mcap
#
# File structure:
#   {base_path}/
#     {entry_name}/
#       {timestamp_us}.mcap
#       {timestamp_us}.meta.json

zenoh:
  mode: peer
  connect:
    endpoints:
      - tcp/localhost:7447

storage:
  backend: filesystem
  filesystem:
    base_path: ${DATA_PATH:-/data/recordings}  # Override with DATA_PATH env var
    file_format: mcap

recorder:
  device_id: ${DEVICE_ID:-robot-001}
  
  flush_policy:
    max_buffer_size_bytes: 10485760  # 10 MB
    max_buffer_duration_seconds: 10
    min_samples_per_flush: 10
  
  compression:
    default_type: none  # MCAP files are already compressed
    default_level: 0
  
  workers:
    flush_workers: 4
    queue_capacity: 1000
  
  control:
    key_prefix: recorder/control
    status_key: recorder/status/**
    timeout_seconds: 30

logging:
  level: info
  format: text

