# Filesystem Backend Example Configuration
# Useful for offline/edge recording scenarios

zenoh:
  mode: peer
  connect:
    endpoints:
      - tcp/localhost:7447

storage:
  backend: filesystem
  filesystem:
    base_path: /data/recordings
    file_format: mcap

recorder:
  device_id: ${DEVICE_ID:-robot-001}
  
  flush_policy:
    max_buffer_size_bytes: 10485760  # 10 MB
    max_buffer_duration_seconds: 10
    min_samples_per_flush: 10
  
  compression:
    default_type: none  # MCAP files are already compressed
    default_level: 0
  
  workers:
    flush_workers: 4
    queue_capacity: 1000
  
  control:
    key_prefix: recorder/control
    status_key: recorder/status/**
    timeout_seconds: 30

logging:
  level: info
  format: text

