# ReductStore Backend Example Configuration

zenoh:
  mode: peer
  connect:
    endpoints:
      - tcp/localhost:7447

storage:
  backend: reductstore
  reductstore:
    url: ${REDUCTSTORE_URL:-http://localhost:8383}
    bucket_name: zenoh_recordings
    api_token: ${REDUCT_API_TOKEN}
    timeout_seconds: 300
    max_retries: 3

recorder:
  device_id: ${DEVICE_ID:-robot-001}
  
  flush_policy:
    max_buffer_size_bytes: 10485760  # 10 MB
    max_buffer_duration_seconds: 10
    min_samples_per_flush: 10
  
  compression:
    default_type: zstd
    default_level: 2
  
  workers:
    flush_workers: 4
    queue_capacity: 1000
  
  control:
    key_prefix: recorder/control
    status_key: recorder/status/**
    timeout_seconds: 30

logging:
  level: info
  format: text

