# ReductStore Backend Example Configuration

[zenoh]
mode = "peer"

[zenoh.connect]
endpoints = [
    "tcp/localhost:7447"
]

[storage]
backend = "reductstore"

[storage.reductstore]
url = "${REDUCTSTORE_URL:-http://localhost:8383}"
bucket_name = "zenoh_recordings"
api_token = "${REDUCT_API_TOKEN}"
timeout_seconds = 300
max_retries = 3

[recorder]
device_id = "${DEVICE_ID:-robot-001}"

[recorder.flush_policy]
max_buffer_size_bytes = 10485760  # 10 MB
max_buffer_duration_seconds = 10
min_samples_per_flush = 10

[recorder.compression]
default_type = "zstd"
default_level = 2

[recorder.workers]
flush_workers = 4
queue_capacity = 1000

[recorder.control]
key_prefix = "recorder/control"
status_key = "recorder/status/**"
timeout_seconds = 30

[logging]
level = "info"
format = "text"

